[package]
name = "cflisp-web"
version = "0.1.0"
authors = ["Samuel Kyletoft <skyletoft@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
cflisp-lib = {path = "../cflisp-lib"}
wasm-bindgen = "0.2.70"
