[package]
name = "cflisp-cli"
version = "0.1.0"
authors = ["Samuel Kyletoft <skyletoft@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"cflisp-lib" = {path = "../cflisp-lib"}

